
--BEGIN
CREATE TABLE produce (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	sn CHAR(32) UNIQUE NOT NULL,
	model CHAR(32) NOT NULL,
	state SMALLINT UNSIGNED NOT NULL,
	date DATE NULL DEFAULT (current_timestamp)
);

CREATE UNIQUE INDEX index_sn ON produce (sn);

CREATE TABLE prod_dcr (
	id INTEGER NOT NULL,
	line SMALLINT UNSIGNED NOT NULL,
	flag SMALLINT UNSIGNED NOT NULL,
	dcr_val FLOAT
);

CREATE TABLE prod_short (
	id INTEGER NOT NULL,
	line_a SMALLINT UNSIGNED NOT NULL,
	line_b SMALLINT UNSIGNED NOT NULL,
	flag SMALLINT UNSIGNED NOT NULL,
	short_val FLOAT
);
--COMMIT;
